apiVersion: v1
kind: Service
metadata:
    name: platformservice-service
    labels:
        name: platformservice-service
        app: microservice
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30010
    selector:
        app: platformservice
        type: microservice